### ISSUE TITLE
Training will continue even when the end goal is achieved?

### ISSUE THREAD

**Issue by ChengshuLi** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#10]
Thank you so much for sharing your work!

I just have a quick question about the following comment:

https://github.com/andrew-j-levy/Hierarchical-Actor-Critc-HAC-/blob/504288596f79ebd5494cfd0978d66e1f7cc7c7df/layer.py#L275-L276

I am wondering why you would want the episode to continue even when the end goal is achieved. Is it because the agent will collect more transitions around the end goal and add them to the experience buffer, and for some reason this helps the training process? 

My second question is that which part of the code implements this mechanism. I haven't got the chance to run your code extensively, so please correct me if I am wrong, but my understanding is that `max_lay_achieved` will be equal to the highest layer (i.e. `self.layer_number`) if end goal is achieved, so `return_to_higher_level` will still return true and terminates the current episode? Why will the highest level policy still be able to set subgoals afterwards?

Thanks a lot!

**Comment by andrew-j-levy** [comment]
Thank you for your comment! Yes, you are correct.  This was actually a comment from a previous version of the code that did not end the episode when the end goal was achieved during training.  In the current version, the episode will always end when the end goal has been achieved.  I will remove this comment from the code.

Thanks!

**Comment by ChengshuLi** [comment]
Thanks for your prompt response!
