### ISSUE TITLE
the Code for Grid World Environment

### ISSUE THREAD

**Issue by dearmrlv** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#13]
Hello my friend! I am interested in your HAC code for the grid world 4-room environment, but unfortunately I cannot find it in the code. I am doing work to figure out how the upper level output the goal for grid-world-like environment, according to your paper of HAC.
Thanks for reading my issue.

**Comment by andrew-j-levy** [comment]
Hello,

Please see attached for the HierQ code.  I have attached code for training agents with 1 (flat), 2, and 3 levels in a four rooms environment.  To train a 3-level agent, move to the “HierQ_3_Levels” folder, and enter the command “python3 initialize_HAC --retrain --mix”.    After the agent has finished training you can watch the trained agent by entering the command, “python3 initialize_HAC.py --test --show”.

Best,
Andrew

[HierQ_Code.zip](https://github.com/andrew-j-levy/Hierarchical-Actor-Critc-HAC-/files/6932191/HierQ_Code.zip)

**Comment by dearmrlv** [comment]
Thanks so much! It is helpful for me!
