### ISSUE TITLE
Question regarding finalize_goal_replay

### ISSUE THREAD

**Issue by krishpop** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#2]
Follow-up question (thanks for taking the time to answer btw). `trans_copy` here (see link below) is a copy of all of the temp_goal_replay_storage, which we set the new target goal to a random goal-state from a transition from that buffer. However, then by iterating over num_trans elements (which is all of the elements in the copy), and setting the goal to that random goal from potentially the middle of the buffer, doesn't this effectively set some of the states (which are reached after the new hindsight "goal") as being transitions which "lead" to this hindsight goal?

Sorry, that was a bit hard to write in words, please let me know if I lost you with that question.

https://github.com/andrew-j-levy/Hierarchical-Actor-Critc-HAC-/blob/master/layer.py#L229-L247

**Comment by andrew-j-levy** [comment]
Yes exactly.  I wanted the agent to learn about actions that lead away from the goal as well as actions that lead to the goal.  In addition, using all the transitions in the temporary buffer should produce more HER transitions that include the sparse reward (reward = 0, discount rate = 0 in this case) as the agent may stay within the threshold of the goal for more than a transition.  I did a small amount of ablation testing with this strategy vs. only including transitions that preceded reaching the goal, and using all the transitions performed better.  But it probably does not make too big of a difference one way or the other.

**Comment by krishpop** [comment]
Ah, okay. that's pretty interesting! Since the actions are technically leading away from that state, I thought the state-action values wouldn't really make sense to be calculated that way. Puzzling...
