### ISSUE TITLE
Code for HierQ

### ISSUE THREAD

**Issue by geranim0** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#5]
Hey, maybe I'm dumb but I can't find code for the HierQ part of the paper. If it's there, how to use it? If not, is there another repo for it? 

Thanks!

**Comment by andrew-j-levy** [comment]
Hello, yes only the HAC portion of the code is available on GitHub right now.  I'll probably upload the HierQ sometime in the future, but feel free to send me an email at andrew_levy2@brown.edu and I can send you the code.  The full pseudocode for HierQ is also provided in the [paper](https://arxiv.org/pdf/1712.00948.pdf).

**Comment by hai-h-nguyen** [comment]
Could you upload the HierQ code? I sent you an email as well.
