### ISSUE TITLE
Use Openai gym to run the code

### ISSUE THREAD

**Issue by ruoqizzz** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#6]
Hi,
I wanna run the code with OpenAI gym env. Is this possible?

**Comment by andrew-j-levy** [comment]
Hello,

This software interfaces with the robotics simulator, MuJoCo, directly so OpenAI Gym is not needed.  The software to run HAC requires (i) a MuJoCo xml file and (ii) a completed "design_agent_and_env.py" file.  The xml files that are used to create the OpenAI Gym MuJoCo environments are available [here](https://github.com/openai/gym/tree/master/gym/envs/mujoco/assets).
