### ISSUE TITLE
Question regarding hyper parameter tuning for gym environments

### ISSUE THREAD

**Issue by nikhilbarhate99** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#7]
Hi,  I have been working on my HAC PyTorch implementation (https://github.com/nikhilbarhate99/Hierarchical-Actor-Critic-HAC-PyTorch) for the Mountain Car env,  but I found the results to be inconsistent. (learns a good policy ~70% of the time).

Can this be fixed by changing some hyper parameters ?
I tried reducing noise, but then it never learns anything useful

Are there any specific things that I should look for while setting the thresholds ? (I am using same threshold for goal and subgoals)

Also, are the thresholds for the 3 level and 2 level policies same?

**Comment by andrew-j-levy** [comment]
Hello, 

Yes the goal thresholds were the same for all levels.  

In your Mountain Car env does the car start at a random place on the mountain or does it always start at the bottom with 0 velocity?  Starting at the bottom with 0 velocity may make the problem too difficult, while random initial states will make exploration easier.

**Comment by nikhilbarhate99** [comment]
The car starts at a random place (in the valley) with velocity 0.

I realised the policy in my implementation was never taking a completely random action. After adding random actions the policy performs significantly better.

**Comment by andrew-j-levy** [comment]
Great.  Yes I have noticed that occasionally executing actions uniformly at random helps significantly as well.

Let me know when you have another environment or two working and I’ll add a link to your repo.
